### ISSUE TITLE
请问下这个是这边编译的

### ISSUE THREAD

**Issue by uglyliu** [XUJINKAI/webhook-bridge#3]
我想增加点通知的字段，貌似直接改modules/msg_parse_gitlab.py文件不生效，应该是要重新把修改的代码编译成二进制吧

**Comment by XUJINKAI** [comment]
python脚本不需要编译，应该是你哪弄错了

**Comment by uglyliu** [comment]
> python脚本不需要编译，应该是你哪弄错了

好的，我再看看，多谢

**Comment by uglyliu** [comment]
> > python脚本不需要编译，应该是你哪弄错了
> 
> 好的，我再看看，多谢

已经可以了，增加了一个Merge行为通知
![image](https://user-images.githubusercontent.com/22983421/183054881-04d8371f-a4b4-45d0-9912-28e42918652c.png)


然后再问大佬一个问题，这个如何设置merge_action == "update" 不发通知啊，我设置成pass，会发一个空的通知

**Comment by XUJINKAI** [comment]
`return None`试试

**Comment by uglyliu** [comment]
> `return None`试试

Okay了，感谢大佬
